# Generated by Django 4.1 on 2023-01-22 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Description', models.TextField(null=True)),
                ('Status', models.BooleanField(default=False)),
                ('Game', models.TextField()),
                ('Modpack', models.CharField(max_length=255, null=True)),
                ('CoverImageLink', models.CharField(max_length=255, null=True)),
                ('DateCreated', models.DateTimeField(default=datetime.datetime(2023, 1, 22, 20, 49, 35, 800689))),
            ],
        ),
    ]
