# Generated by Django 4.1 on 2023-01-23 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Warden_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 23, 17, 49, 12, 431534)),
        ),
    ]
